#define MASQUERADE_MAX_LEVEL 10 // TFN EDIT CHANGE - ORIGINAL: #define MASQUERADE_MAX_LEVEL 25 - You Breach or You Don't

#define MASQUERADE_REASON_PREFERENCES "Preferences"
#define MASQUERADE_REASON_NPC "NPC"
#define MASQUERADE_REASON_OBJECT "Object"
#define MASQUERADE_REASON_OTHER "Other"
